// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WwcUrpApi.Models;

namespace wwcurpapi.Migrations
{
    [DbContext(typeof(UrpContext))]
    partial class UrpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WwcUrpApi.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BirthYear");

                    b.Property<string>("CommonName");

                    b.Property<string>("Description");

                    b.Property<string>("FullName");

                    b.Property<int?>("PronounId");

                    b.HasKey("PersonId");

                    b.HasIndex("PronounId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("WwcUrpApi.Models.Pronoun", b =>
                {
                    b.Property<int>("PronounId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Object");

                    b.Property<string>("Posessive");

                    b.Property<string>("Subject");

                    b.HasKey("PronounId");

                    b.ToTable("Pronoun");
                });

            modelBuilder.Entity("WwcUrpApi.Models.Person", b =>
                {
                    b.HasOne("WwcUrpApi.Models.Pronoun", "Pronoun")
                        .WithMany()
                        .HasForeignKey("PronounId");
                });
#pragma warning restore 612, 618
        }
    }
}
