version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # - run: |
      #     ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      # build image
      - run: |
          docker info
          docker build -t aspnetapp -f Dockerfile .
      # deploy the image
      - run: |
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a $HEROKU_APP_NAME

      - run: |
          chmod +x .circleci/setup-heroku.sh
          .circleci/setup-heroku.sh
      - run: |
          heroku container:release web --app $HEROKU_APP_NAME
